Add infiniband support.
indigo-dc/cloud-info-provider-deep pull request #2
Opened 2018-08-22 11:23 UTC by orviz

+ Through flavor's extra_specs parsing.
+ Metadata key&value is specified under:
    templates>extra_specs>infiniband
  in configuration file.
+ Only if key&value match with the values in the configuration,
  the infiniband support is published.
+ Currently available through GLUE2ExecutionEnvironmentNetworkInfo.

2018-10-11 08:44 UTC, alvarolopez requested changes

2018-10-11 08:44 UTC, alvarolopez commented on etc/sample.openstack.yaml
> +            extra_specs:
This should be removed, as the static information and its defaults are going to be added if there is no such extra_spec in the flavor (i.e. by default all flavors would have infiniband!)

2018-10-11 08:44 UTC, alvarolopez commented on cloud_info/providers/openstack.py
> +                template_ib = (True if flavor_ib_v == extra_specs_ib['value']
This line can be changed to `template-ib = flavor_ib_v == extra_specs_ib['value']` (the rest is not needed)

2018-10-16 12:47 UTC, orviz commented
@alvarolopez @aidaph the requested changes have been addressed. The new command line opts, `extra-specs-infiniband-key` and  `extra-specs-infiniband-value`, allow easier provision of required info

2018-10-16 12:50 UTC, orviz commented
Just realized this PR is to be merged in master while it should be done against DEEP branch

2018-10-16 12:50 UTC, closed without merging